export const FETCH_POSTS_LOADING = 'FETCH_POSTS_LOADING'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const CREATE_POST_LOADING = 'CREATE_POST_LOADING'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const UPDATE_POST_LOADING = 'UPDATE_POST_LOADING'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const DELETE_POST_LOADING = 'DELETE_POST_LOADING'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const LIKE_POST_LOADING = 'LIKE_POST_LOADING'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR'

export const SEARCH_POSTS_LOADING = 'SEARCHING_POSTS_LOADING'
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS'
export const SEARCH_POSTS_ERROR = 'SEARCH_POSTS_ERROR'